// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzOW8QaXQsR5312Gbe91pMOZ3KwT7yQ4E',
    appId: '1:818577713656:web:af61a5566b7bd2038e0e0d',
    messagingSenderId: '818577713656',
    projectId: 'chatbot-414ba',
    authDomain: 'chatbot-414ba.firebaseapp.com',
    storageBucket: 'chatbot-414ba.firebasestorage.app',
    measurementId: 'G-JM8781T26W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH_sW6W8WcI3YnpkqMjc7PChnq2_8wECU',
    appId: '1:818577713656:android:1659335641d159ab8e0e0d',
    messagingSenderId: '818577713656',
    projectId: 'chatbot-414ba',
    storageBucket: 'chatbot-414ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy5a1ibtApDj7G7VRzcfeDP1XicuygUFc',
    appId: '1:818577713656:ios:4b17741687cbb2d48e0e0d',
    messagingSenderId: '818577713656',
    projectId: 'chatbot-414ba',
    storageBucket: 'chatbot-414ba.firebasestorage.app',
    iosBundleId: 'com.example.aichat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy5a1ibtApDj7G7VRzcfeDP1XicuygUFc',
    appId: '1:818577713656:ios:4b17741687cbb2d48e0e0d',
    messagingSenderId: '818577713656',
    projectId: 'chatbot-414ba',
    storageBucket: 'chatbot-414ba.firebasestorage.app',
    iosBundleId: 'com.example.aichat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzOW8QaXQsR5312Gbe91pMOZ3KwT7yQ4E',
    appId: '1:818577713656:web:90578ed57b7dccb28e0e0d',
    messagingSenderId: '818577713656',
    projectId: 'chatbot-414ba',
    authDomain: 'chatbot-414ba.firebaseapp.com',
    storageBucket: 'chatbot-414ba.firebasestorage.app',
    measurementId: 'G-G9H0HJNED3',
  );
}
